# Spam Filter

In [1]:
#Import Packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
# import data
spam_df = pd.read_csv("spam.csv")

In [3]:
spam_df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
spam_df.groupby('Category')

In [7]:
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [8]:
#we have 4825 normal msg (4516 are unique ,,)most frequent are sorry i ll 
#call later

In [ ]:
# we create a new column 'spam'

In [11]:
#turn spam/ham into numerical data , creating a new column called 'spam'
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [12]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [16]:
# Create train/test split
x_train, x_test , y_train, y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.25)

In [17]:
x_train

604                Be happy there. I will come after noon
3984    Nationwide auto centre (or something like that...
2698    Can you use foreign stamps for whatever you se...
2835                        U sick still can go shopping?
1179    I'm outside islands, head towards hard rock an...
                              ...                        
4874                           Lol! Oops sorry! Have fun.
4399    Can you tell Shola to please go to college of ...
5218            I accidentally brought em home in the box
4184                    Sorry, I'll call later in meeting
395     Pick you up bout 7.30ish? What time are  and t...
Name: Message, Length: 4179, dtype: object

In [18]:
x_train.describe()

count                       4179
unique                      3921
top       Sorry, I'll call later
freq                          21
Name: Message, dtype: object

In [19]:
# find word cound and store data as a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [21]:
x_train_count

<4179x7512 sparse matrix of type '<class 'numpy.int64'>'
	with 55568 stored elements in Compressed Sparse Row format>

In [23]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
# train model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [27]:
#pre-test ham
email_ham = ['hey wanna meet up for the game ?']
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

0 ==> Not spam 

In [29]:
#pre_test spam
email_spam = ["reward money click "]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

1 ==> Spam

In [32]:
email = ["baseball tickets later"]
email_count = cv.transform(email)
model.predict(email_count)

array([0], dtype=int64)

In [34]:
# test model
x_test_count = cv.transform(x_test)
model.score(x_test_count,y_test)

0.9834888729361091